spring:
  application:
    name: APPOINTMENT-SERVICE

  data:
    mongodb:
      uri: mongodb://localhost:27017/PractoAppointment




  profiles:
    active: dev
    server:
      port: 8087

  eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka








